### ISSUE TITLE
Implement Code Snippet from SoTellUs

### ISSUE THREAD

**Issue by BigActual** [realbig/VanDamTheme#6]
Hold on

**Comment by joelworsham** [comment]
Here's some mocks.

![Uploading nav-sidebar-alt.jpg…]()
![nav-sidebar-alt2](https://cloud.githubusercontent.com/assets/4182573/21733581/52388ccc-d42d-11e6-80a1-1fb5c1591c61.jpg)
![Uploading nav-sidebar.jpg…]()
![sidebar-top-alt](https://cloud.githubusercontent.com/assets/4182573/21733584/5238f518-d42d-11e6-8c91-2feec0507916.jpg)
![sidebar-top](https://cloud.githubusercontent.com/assets/4182573/21733580/52379830-d42d-11e6-9d95-3f2f1ecad86d.jpg)

**Comment by BigActual** [comment]
Apologies for the delay: Here's the snippet from the client:
Embed My Reviews to My Website

Javascript
Use this to embed on any page of your existing site
Widget Size: 254px wide by 422 px tall

Code
Preview
Use this to embed on any page of your existing site

<script src="https://sotellus.com/js/sotellus_widget.js?client=vandam-and-krusinga-building-and-restoration&amp;width=254&amp;height=422" async></script>
Page Size: 100% wide by 500 px tall

Code
Preview
Use this to embed on any page of your existing site

<script src="https://sotellus.com/js/sotellus_widget.js?client=vandam-and-krusinga-building-and-restoration&amp;width=100%25&amp;height=500" async></script>
Alternate Version: IFRAME
If the JAVASCRIPT version doesn't work, try this IFRAME version.
WORDPRESS Users should use this iFrame version PLUS the iFrame Wordpress Plugin. (Note: <iframe...></iframe> becomes [iframe...])
Widget Size: 254px wide by 422 px tall

Code
Preview
Use this to embed on any page of your existing site

<iframe src="https://sotellus.com/iframe/vandam-and-krusinga-building-and-restoration/" id="stuif01" width="254" height="422"></iframe>
Page Size: 100% wide by 500 px tall

Code
Preview
Use this to embed on any page of your existing site

<iframe src="https://sotellus.com/iframe/vandam-and-krusinga-building-and-restoration/" id="stuifw01" scrolling="yes" width="100%" height="500"></iframe>

**Comment by BigActual** [comment]
Note the iFrame Wordpress reference  3/4ths down the page.

**Comment by joelworsham** [comment]
It's more than a button: http://d.pr/i/Bned

Thoughts?

**Comment by BigActual** [comment]
What happens if you click said box?

**Comment by joelworsham** [comment]
Top of box takes you their sotellus page, bottom of box takes to sotellus homepage.

**Comment by BigActual** [comment]
When you have a minute, would you please add a few pixels of padding below the widget so that the word Testimonials isn't quite so close. I'd really appreciate it if the amount of space between the two is approximately the same as between the columns. Thanks. BTW> Client adores the work you did. Thanks.

**Comment by joelworsham** [comment]
No problem! Glad they're satisfied. I've added some padding, let me know your thoughts.

**Comment by BigActual** [comment]
Thanks
